--Cwiczenia 5

--1
describe dict;

--2
SELECT * FROM dict
WHERE COMMENTS LIKE '%column%';

--3
describe USER_OBJECTS;

--4
SELECT OBJECT_NAME, OBJECT_TYPE, CREATED FROM USER_OBJECTS
ORDER BY OBJECT_TYPE;

--5
describe USER_TABLES;

--6
SELECT * FROM USER_TABLES;

--7
describe USER_TAB_COLUMNS;

--8
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='EMPLOYEES';

--9
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='DUAL';

--10
describe user_constraints;

--11
SELECT * FROM user_constraints WHERE TABLE_NAME='EMPLOYEES';

--12
CREATE TABLE Ksiazki
(
    ksiazka_id NUMBER(5) PRIMARY KEY,
    tytul VARCHAR2(20),
    styl VARCHAR(20)
);

--13
CREATE INDEX IX_Styl ON Ksiazki(styl);

--14
SELECT * FROM USER_INDEXES
WHERE Table_NAME='KSIAZKI';

--15
CREATE OR REPLACE SYNONYM DZIAL FOR DEPARTMENTS;
SELECT * FROM USER_SYNONYMS;

--16
CREATE OR REPLACE VIEW EMPLOYEES60 AS 
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=60;
SELECT * FROM USER_VIEWS;

--17
SELECT * FROM USER_ROLE_PRIVS;

--18
SELECT * FROM USER_SYS_PRIVS;

--19
SELECT * FROM USER_TAB_PRIVS_RECD;

--20
SELECT * FROM ALL_SYNONYMS;

--21
SELECT * FROM USER_PROCEDURES;

--22
SELECT * FROM ALL_PROCEDURES
WHERE owner!='homeuser';

--23
CREATE TABLE STUDENCI
(
    id_stud NUMBER(6) PRIMARY KEY,
    imie VARCHAR2(30),
    nazwisko VARCHAR2(30),
    kierunek VARCHAR(30),
    semestr NUMBER(2)
);
CREATE TABLE EGZAMINY
(
    id_egz NUMBER(6) PRIMARY KEY,
    przedmiot VARCHAR2(30),
    ocena NUMBER(2), CONSTRAINT ocena CHECK (ocena BETWEEN 1 AND 5),
    id_stud NUMBER(6) REFERENCES STUDENCI(id_stud)
)
--24
INSERT INTO STUDENCI VALUES (1,'Adam','Mickiewicz','Polonistyka', 4);
INSERT INTO STUDENCI VALUES (2,'Juliusz','Slowacki','Polonistyka',3);
INSERT INTO EGZAMINY VALUES (1,'Polski',5,1);
INSERT INTO EGZAMINY VALUES (2,'Polski',3,2);
INSERT INTO EGZAMINY VALUES (3,'Matematyka',2,1);

SELECT * FROM STUDENCI;
SELECT * FROM EGZAMINY;

--25
SELECT * FROM USER_OBJECTS;

--26
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EGZAMINY';

--27
--utworzenia u¿ytkownika
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER labXX IDENTIFIED BY password12;

--sprawdzenie
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE ='LABXX' AND PRIVILEGE = 'SELECT' AND TABLE_NAME IN ('STUDENCI','EGZAMINY');

--28
GRANT SELECT ON studenci TO labXX;
GRANT SELECT ON egzaminy TO labXX;

--29
GRANT INSERT ON studenci TO labXX;
GRANT INSERT ON egzaminy TO labXX;
GRANT UPDATE ON studenci TO labXX;
GRANT UPDATE ON egzaminy TO labXX;

--30
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE ='LABXX' AND PRIVILEGE = 'INSERT' AND TABLE_NAME='STUDENCI';

--32
REVOKE UPDATE ON STUDENCI FROM labXX;

--33
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE ='LABXX' AND PRIVILEGE = 'UPDATE' AND TABLE_NAME='STUDENCI';

--34
GRANT UPDATE(OCENA) ON EGZAMINY TO labXX;
SELECT * FROM DBA_COL_PRIVS WHERE GRANTEE ='LABXX';

--38
DROP TABLE imiona;
CREATE TABLE imiona
(
    id NUMBER GENERATED AS IDENTITY,
    val VARCHAR2(10)
 );
INSERT INTO imiona(val) VALUES('Adam');
COMMIT;

--39
SELECT * FROM USER_SEQUENCES;
--pojawia sie sekwencja o nazwie ISEQ$$_74094


--40
SELECT TABLE_NAME, COLUMN_NAME, DATA_DEFAULT FROM USER_TAB_COLUMNS;

